---
# The role binding to combine the no-access service account and role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: no-access-rb
subjects:
- kind: ServiceAccount
  name: no-access-sa
roleRef:
  kind: Role
  name: no-access-role
  apiGroup: rbac.authorization.k8s.io

---
# The role binding to combine the secret-access service account and role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: secret-access-rb
subjects:
- kind: ServiceAccount
  name: secret-access-sa
roleRef:
  kind: Role
  name: secret-access-role
  apiGroup: rbac.authorization.k8s.io